In [3]:
import numpy as np

In [4]:
a=np.array(range(10))

In [5]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
a[a==9]=0

In [9]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 0])

In [10]:
b=a

In [12]:
b[b==0]=11

In [13]:
b

array([11,  1,  2,  3,  4,  5,  6,  7,  8, 11])

In [14]:
a

array([11,  1,  2,  3,  4,  5,  6,  7,  8, 11])

In [15]:
c=np.copy(a)

In [18]:
c.shape

(10,)

In [19]:
c[c==11]=56

In [20]:
c

array([56,  1,  2,  3,  4,  5,  6,  7,  8, 56])

In [21]:
a

array([11,  1,  2,  3,  4,  5,  6,  7,  8, 11])

In [22]:
b

array([11,  1,  2,  3,  4,  5,  6,  7,  8, 11])

In [23]:
c[c!=1]=80

In [24]:
c

array([80,  1, 80, 80, 80, 80, 80, 80, 80, 80])

In [26]:
c[c==80]

array([80, 80, 80, 80, 80, 80, 80, 80, 80])

In [27]:
c**2

array([6400,    1, 6400, 6400, 6400, 6400, 6400, 6400, 6400, 6400],
      dtype=int32)

In [28]:
a=np.array(range(6)).reshape(2,3)

In [29]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [30]:
a**2

array([[ 0,  1,  4],
       [ 9, 16, 25]], dtype=int32)

In [33]:
(a[:,1:]**2).sum()

46